# Generated by Django 5.2.6 on 2025-09-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("currency_id", models.AutoField(primary_key=True, serialize=False)),
                ("currency_short_name", models.CharField(max_length=11)),
                ("currency_long_name", models.CharField(max_length=50)),
            ],
        ),
    ]
