# Generated by Django 5.2.6 on 2025-11-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("currency_id", models.AutoField(primary_key=True, serialize=False)),
                ("currency_short_name", models.CharField(max_length=11)),
                ("currency_long_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("gender", models.CharField(max_length=11)),
                ("age", models.IntegerField(default=0)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="user.currency"
                    ),
                ),
            ],
        ),
    ]
