# Generated by Django 5.2.6 on 2025-12-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="currency_long_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=32),
        ),
    ]
