# Generated by Django 5.2.6 on 2025-09-26 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saving",
            old_name="savingid",
            new_name="saving_id",
        ),
        migrations.RenameField(
            model_name="savinggoal",
            old_name="savinggoalid",
            new_name="saving_goal_id",
        ),
        migrations.RenameField(
            model_name="savinggoal",
            old_name="targetamount",
            new_name="target_amount",
        ),
        migrations.RenameField(
            model_name="savinggoal",
            old_name="targetdate",
            new_name="target_date",
        ),
    ]
