# Generated by Django 5.2.6 on 2025-11-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("reminder_id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.CharField(max_length=150)),
                ("date_time", models.DateTimeField()),
                ("status", models.BooleanField(null=True)),
                ("date_responded", models.DateField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
    ]
