# Generated by Django 5.2.6 on 2025-12-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
