# Generated by Django 5.2.6 on 2025-12-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_reminder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_responded',
            field=models.DateTimeField(null=True),
        ),
    ]
