# Generated by Django 5.2.6 on 2025-12-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('expense', '0002_alter_expense_user_alter_expensecategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='budgets', to='expense.expensecategory'),
        ),
    ]
