# Generated by Django 5.2.6 on 2025-09-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='user_id',
            new_name='user',
        ),
    ]
