# Generated by Django 5.2.6 on 2025-12-17 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_budget_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
